/* Regenerates fileicons.gen.ts — the file icons the editor tree, tab strip and
   FILES panel draw. Add an extension to EXT (or a whole filename to NAME), then
   from bridge/dashboard/web: node src/lib/fileicons.build.mjs

   Values are lucide icon names; browse them at lucide.dev/icons. Lucide because
   that is the icon language the rest of the HUD already speaks — 24px grid,
   currentColor stroke, round caps — so a file row sits next to the toolbar
   glyphs without reading as an import from another app. Category, not language:
   .py and .rs share file-code, and the extension in the filename right beside
   it carries which one. Bodies are inlined rather than pulled from a package so
   the dashboard keeps working offline. */
import { writeFileSync } from "node:fs";

const EXT = {
  ts: "file-code", mts: "file-code", cts: "file-code", tsx: "file-code",
  js: "file-code", mjs: "file-code", cjs: "file-code", jsx: "file-code",
  py: "file-code", rs: "file-code", go: "file-code", rb: "file-code",
  php: "file-code", java: "file-code", c: "file-code", h: "file-code",
  cpp: "file-code", cc: "file-code", hpp: "file-code", cs: "file-code",
  swift: "file-code", kt: "file-code", lua: "file-code", dart: "file-code",
  vue: "file-code", svelte: "file-code", astro: "file-code",
  graphql: "file-code", gql: "file-code", prisma: "file-code", proto: "file-code",
  ipynb: "notebook",
  html: "code-xml", htm: "code-xml", xml: "code-xml", svg: "code-xml",
  css: "brush", scss: "brush", sass: "brush", less: "brush",
  json: "braces", jsonc: "braces",
  yml: "file-cog", yaml: "file-cog", toml: "file-cog", ini: "file-cog",
  cfg: "file-cog", conf: "file-cog", editorconfig: "file-cog",
  md: "file-text", mdx: "file-text", txt: "file-text", rst: "file-text",
  license: "file-text", tex: "file-text", pdf: "file-text", docx: "file-text",
  xlsx: "file-spreadsheet",
  sh: "file-terminal", bash: "file-terminal", zsh: "file-terminal",
  fish: "file-terminal", ps1: "file-terminal", makefile: "file-terminal",
  dockerfile: "container",
  gitignore: "git-branch", gitattributes: "git-branch", gitmodules: "git-branch",
  png: "image", jpg: "image", jpeg: "image", gif: "image", webp: "image",
  bmp: "image", avif: "image", ico: "image",
  zip: "file-archive", tar: "file-archive", gz: "file-archive", tgz: "file-archive",
  xz: "file-archive", bz2: "file-archive", "7z": "file-archive", rar: "file-archive",
  sql: "database", db: "database", sqlite: "database", sqlite3: "database",
  env: "file-lock",
  log: "scroll-text", todo: "list-todo", wasm: "binary",
};
const NAME = {
  "package.json": "package", "package-lock.json": "package", "yarn.lock": "package",
  "tsconfig.json": "file-cog",
};

const all = [...new Set([...Object.values(EXT), ...Object.values(NAME), "file"])];
const data = await fetch(`https://api.iconify.design/lucide.json?icons=${all.join(",")}`).then((r) => r.json());

const missing = all.filter((n) => !data.icons?.[n] && !data.aliases?.[n]);
if (missing.length) { console.error("MISSING:", missing.join(", ")); process.exit(1); }

// Aliases come back separately, pointing at a parent's body. Lucide draws at
// stroke-width 2; the HUD's own glyphs are 1.5–1.6, so thin them to match.
const body = (n) => (data.icons[n]?.body ?? data.icons[data.aliases?.[n]?.parent]?.body)
  .replaceAll('stroke-width="2"', 'stroke-width="1.6"');
const entries = all.map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(body(n))},`).join("\n");
const map = (o) => Object.entries(o).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n");

writeFileSync(new URL("fileicons.gen.ts", import.meta.url), `\
/* GENERATED by fileicons.build.mjs — edit the maps there and re-run it, not this.
   Icon bodies are from the lucide set (ISC), fetched via api.iconify.design. */

/* Last dot-segment of the filename → icon. For an extensionless name like
   Dockerfile or Makefile that segment is the whole lowercased name, so those
   land here too. */
export const EXT_ICON: Record<string, string> = {
${map(EXT)}
};

/* Whole-filename overrides, where the extension alone would undersell it. */
export const NAME_ICON: Record<string, string> = {
${map(NAME)}
};

export const ICON_BODY: Record<string, string> = {
${entries}
};
`);
console.log(`ok — ${all.length} icons`);
