/* Regenerates fileicons.gen.ts — the file icons the editor tree, tab strip and
   FILES panel draw. Add an extension to EXT (or a whole filename to NAME), then
   from bridge/dashboard/web: node src/lib/fileicons.build.mjs

   Values are vscode-icons names minus the "file-type-" prefix; browse them at
   icon-sets.iconify.design/vscode-icons. Bodies are inlined rather than pulled
   from a package so the dashboard keeps working offline. */
import { writeFileSync } from "node:fs";

const EXT = {
  ts: "typescript", mts: "typescript", cts: "typescript", tsx: "reactts",
  js: "js", mjs: "js", cjs: "js", jsx: "reactjs",
  py: "python", rs: "rust", go: "go", rb: "ruby", php: "php", java: "java",
  c: "c", h: "cheader", cpp: "cpp", cc: "cpp", hpp: "cppheader", cs: "csharp",
  swift: "swift", kt: "kotlin", lua: "lua", dart: "dartlang",
  vue: "vue", svelte: "svelte", astro: "astro", html: "html", htm: "html", xml: "xml",
  json: "json", jsonc: "json",
  css: "css", scss: "scss", sass: "sass", less: "less",
  md: "markdown", mdx: "markdown", txt: "text", rst: "text", pdf: "pdf2",
  yml: "yaml", yaml: "yaml", toml: "toml", ini: "config", cfg: "config", conf: "config",
  editorconfig: "editorconfig", gitignore: "git", gitattributes: "git", gitmodules: "git",
  dockerfile: "docker", makefile: "shell",
  sh: "shell", bash: "shell", zsh: "shell", fish: "shell", ps1: "powershell",
  png: "image", jpg: "image", jpeg: "image", gif: "image", webp: "image", bmp: "image",
  avif: "image", ico: "favicon", svg: "svg",
  zip: "zip", tar: "zip", gz: "zip", tgz: "zip", xz: "zip", bz2: "zip", "7z": "zip", rar: "zip",
  sql: "sql", db: "sqlite", sqlite: "sqlite", sqlite3: "sqlite",
  env: "dotenv",
  license: "text", log: "log", todo: "todo",
  xlsx: "excel", docx: "word", ipynb: "jupyter",
  graphql: "graphql", gql: "graphql", prisma: "prisma", wasm: "wasm", proto: "protobuf", tex: "tex",
};
const NAME = {
  "package.json": "npm", "package-lock.json": "npm", "tsconfig.json": "tsconfig", "yarn.lock": "yarn",
};

const known = new Set(await fetch("https://api.iconify.design/collection?prefix=vscode-icons")
  .then((r) => r.json())
  .then((d) => [...(d.uncategorized ?? []), ...(d.hidden ?? []), ...Object.keys(d.aliases ?? {})]));

const wanted = [...new Set([...Object.values(EXT), ...Object.values(NAME)])].map((s) => `file-type-${s}`);
const missing = wanted.filter((n) => !known.has(n));
if (missing.length) { console.error("MISSING:", missing.join(", ")); process.exit(1); }

const all = [...wanted, "default-file"];
const data = await fetch(`https://api.iconify.design/vscode-icons.json?icons=${all.join(",")}`).then((r) => r.json());

// Aliases come back separately, pointing at a parent's body.
const body = (n) => data.icons[n]?.body ?? data.icons[data.aliases?.[n]?.parent]?.body;
const short = (n) => n.replace(/^file-type-/, "");
const entries = all.map((n) => `  ${JSON.stringify(short(n))}: ${JSON.stringify(body(n))},`).join("\n");
const map = (o) => Object.entries(o).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n");

// These render at 13px — a body over ~9KB is detail nobody can see, paid for on
// every load. Pick a simpler stand-in in EXT instead of shipping it.
const fat = all.filter((n) => (body(n)?.length ?? 0) > 9000);
if (fat.length) console.error("TOO BIG, pick a simpler icon:", fat.map((n) => `${n} (${(body(n).length / 1024).toFixed(1)}K)`).join(", "));

// Everything is 32x32 bar the odd import (the Go gopher); those carry their own.
const boxes = Object.fromEntries(all
  .map((n) => [short(n), data.icons[n] ?? data.icons[data.aliases?.[n]?.parent] ?? {}])
  .filter(([, i]) => (i.width ?? data.width) !== 32 || (i.height ?? data.height) !== 32)
  .map(([k, i]) => [k, `0 0 ${i.width ?? data.width} ${i.height ?? data.height}`]));

writeFileSync(new URL("fileicons.gen.ts", import.meta.url), `\
/* GENERATED by fileicons.build.mjs — edit the maps there and re-run it, not this.
   Icon bodies are from the vscode-icons set (MIT), fetched via api.iconify.design. */

/* Last dot-segment of the filename → icon. For an extensionless name like
   Dockerfile or Makefile that segment is the whole lowercased name, so those
   land here too. */
export const EXT_ICON: Record<string, string> = {
${map(EXT)}
};

/* Whole-filename overrides, where the extension alone would undersell it. */
export const NAME_ICON: Record<string, string> = {
${map(NAME)}
};

export const ICON_BODY: Record<string, string> = {
${entries}
};

/* Only for icons that aren't 32x32; everything else uses that default. */
export const ICON_VIEWBOX: Record<string, string> = {
${map(boxes)}
};
`);
console.log(`ok — ${all.length} icons`);
