"""Dev servers: long-lived background processes owned by the bridge.

One server per run directory, so several projects / worktrees / branches can be
previewed at the same time. Each server detects the localhost URL the framework
actually bound (dev servers auto-pick the next free port when the default is
busy) by scanning its own output, and that detected URL is what the preview
surface points at.

Legacy single-server helpers (``start_server``/``stop_server``/``server_state``/
``log_tail``/``server_status``) operate on the most-recently-started server so
the Mini App and Telegram surfaces keep working unchanged.
"""

import os
import re
import signal
import subprocess
import threading
import time
from collections import deque

from bridge import config, pubsub, state
from bridge.browser import rel
from bridge.telegram import send

# Dev-server logs are also teed to this file *inside the project* so a Claude
# session running in the same cwd can simply read it (e.g. `tail .mystical/dev.log`).
DEV_LOG_REL = os.path.join(".mystical", "dev.log")

MAX_SERVERS = 8           # runaway guard (concurrent dev servers)
DETECT_TIMEOUT = 8.0      # how long start() waits for the URL before returning

_ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")
_URL_RE = re.compile(r"https?://(?:localhost|127\.0\.0\.1|0\.0\.0\.0):(\d{2,5})")

_servers: "dict[str, DevServer]" = {}   # keyed by realpath(cwd)
_primary: "str | None" = None           # last-started cwd — backs the legacy API
_lock = threading.Lock()


def _safe_rel(path: str) -> str:
    try:
        return rel(path)
    except Exception:  # noqa: BLE001
        return path


def _detect_url(line: str):
    """Parse a `http://localhost:PORT` (or 127.0.0.1 / 0.0.0.0) URL out of a log
    line, normalising the host to localhost. Returns (url, port) or None."""
    m = _URL_RE.search(_ANSI_RE.sub("", line))
    if not m:
        return None
    port = int(m.group(1))
    return f"http://localhost:{port}", port


def _mystical_dir(cwd: str) -> str:
    """<cwd>/.mystical, created on demand and self-ignored from git."""
    d = os.path.join(cwd, ".mystical")
    os.makedirs(d, exist_ok=True)
    gi = os.path.join(d, ".gitignore")
    if not os.path.exists(gi):
        with open(gi, "w", encoding="utf-8") as f:
            f.write("*\n")  # the .mystical dir never shows up in git status
    return d


def _open_logfile(cwd: str):
    """Open <cwd>/.mystical/dev.log (truncating). Best-effort: returns the file
    handle, or None if it can't be created."""
    try:
        return open(os.path.join(_mystical_dir(cwd), "dev.log"), "w",
                    encoding="utf-8", buffering=1)
    except OSError:
        return None


# --- selector injection ------------------------------------------------------
# Element-select in the preview needs the mysticalSelector vite plugin running
# inside the previewed app (in-page agent + frame-ancestors CSP). Instead of
# asking every project to add it, the bridge injects it into any vite project it
# starts: a wrapper config in .mystical/ (git-ignored) layers the plugin over the
# project's own vite config, and the dev command gets `--config` pointed at it.
# The project's files are never modified — stop the server and no trace remains.

_PLUGIN_DIST = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                            "tools", "selector-plugin", "dist", "vite-plugin.mjs")
_VITE_CONFIGS = ("vite.config.ts", "vite.config.js", "vite.config.mjs",
                 "vite.config.mts", "vite.config.cjs", "vite.config.cts")
SELECTOR_CFG_REL = ".mystical/vite.selector.config.mjs"

_WRAPPER_TMPL = """\
// generated by the mystical bridge on dev-server start — temporary element-selector
// injection for the preview iframe. Not part of the project (dir is git-ignored).
import base from "{base}";
import {{ mysticalSelector }} from "{plugin}";

export default async (env) => {{
  const b = await (typeof base === "function" ? base(env) : base);
  return {{ ...b, plugins: [...(b.plugins ?? []), mysticalSelector({{ parentOrigins: [{origins}] }})] }};
}};
"""


def _parent_origins() -> list:
    """Origins allowed to iframe the injected dev server (dashboard + Mini App,
    plus the named preview tunnel when configured)."""
    origins = [f"http://{h}:{p}" for p in sorted({config.DASH_PORT, config.MINIAPP_PORT})
               for h in ("localhost", "127.0.0.1")]
    if config.PREVIEW_HOSTNAME:
        origins.append(f"https://{config.PREVIEW_HOSTNAME}")
    return origins


def _selector_cmd(cwd: str, cmd: str) -> str:
    """Return ``cmd`` extended to load the selector wrapper config when ``cwd``
    is a vite project; unchanged (never raises) in every other case."""
    try:
        if "--config" in cmd or ".mystical" in cmd or not os.path.exists(_PLUGIN_DIST):
            return cmd
        base = next((f for f in _VITE_CONFIGS
                     if os.path.exists(os.path.join(cwd, f))), None)
        if base is None:
            return cmd
        with open(os.path.join(cwd, base), encoding="utf-8") as f:
            if "mysticalSelector" in f.read():
                return cmd  # project already runs the plugin (e.g. this repo's dashboard)
        # ponytail: npm/pnpm/yarn/bun/npx/vite covers real dev commands; anything
        # else runs without injection rather than risk breaking the server.
        if re.search(r"\bnpm\s+run\s", cmd):
            sep = " " if " -- " in cmd else " -- "   # npm forwards args only after --
        elif re.search(r"\b(pnpm|yarn|bun|npx|vite)\b", cmd):
            sep = " "                                # these forward options directly
        else:
            return cmd
        origins = ", ".join(f'"{o}"' for o in _parent_origins())
        with open(os.path.join(_mystical_dir(cwd), "vite.selector.config.mjs"),
                  "w", encoding="utf-8") as f:
            f.write(_WRAPPER_TMPL.format(base=os.path.join(cwd, base),
                                         plugin=_PLUGIN_DIST, origins=origins))
        return f"{cmd}{sep}--config {SELECTOR_CFG_REL}"
    except Exception:  # noqa: BLE001 — injection is best-effort, never block a start
        return cmd


class DevServer:
    def __init__(self, cwd: str, cmd: str, project: str, branch: str):
        self.cwd = cwd
        self.cmd = cmd
        self.project = project
        self.branch = branch
        self.created = time.time()
        self.log: deque = deque(maxlen=300)
        self._log_lock = threading.Lock()   # reader appends while state()/tail read
        self.url: "str | None" = None
        self.port: "int | None" = None
        self.logfile = _open_logfile(cwd)
        self.proc = subprocess.Popen(
            cmd, cwd=cwd, shell=True, stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT, text=True, bufsize=1,
            start_new_session=True)
        threading.Thread(target=self._reader, daemon=True).start()

    def alive(self) -> bool:
        return self.proc.poll() is None

    def _reader(self) -> None:
        if self.proc.stdout:
            for line in self.proc.stdout:
                line = line.rstrip("\n")
                with self._log_lock:
                    self.log.append(line)
                if self.url is None:
                    hit = _detect_url(line)
                    if hit:
                        self.url, self.port = hit
                if self.logfile is not None:
                    try:
                        self.logfile.write(line + "\n")
                    except (OSError, ValueError):
                        pass
                pubsub.publish("logs", {"line": line, "dir": _safe_rel(self.cwd)})
        self._close_logfile()

    def _close_logfile(self) -> None:
        if self.logfile is not None:
            try:
                self.logfile.close()
            except OSError:
                pass
            self.logfile = None

    def tail(self, n: int) -> list:
        with self._log_lock:      # snapshot under the lock — reader appends concurrently
            return list(self.log)[-n:]

    def state(self) -> dict:
        running = self.alive()
        return {
            "status": "running" if running else "exited",
            "cmd": self.cmd,
            "dir": _safe_rel(self.cwd),
            "pid": self.proc.pid if running else None,
            "url": self.url,
            "port": self.port,
            "project": self.project,
            "branch": self.branch,
            "tail": self.tail(12),
        }

    def terminate(self) -> None:
        try:
            os.killpg(os.getpgid(self.proc.pid), signal.SIGTERM)
            self.proc.wait(timeout=8)
        except (ProcessLookupError, PermissionError):
            pass
        except subprocess.TimeoutExpired:
            try:
                os.killpg(os.getpgid(self.proc.pid), signal.SIGKILL)
                self.proc.wait(timeout=5)     # reap the killed group leader
            except (OSError, subprocess.TimeoutExpired):
                pass
        self._close_logfile()


def _not_started(cwd: "str | None") -> dict:
    return {"status": "not started", "cmd": None,
            "dir": _safe_rel(cwd) if cwd else None, "pid": None,
            "url": None, "port": None, "project": "", "branch": "", "tail": []}


# --- registry API (keyed by run directory) ---------------------------------

def start(cwd: str, cmd: str, project: str = "", branch: str = "") -> str:
    """Start a dev server in ``cwd`` (no-op if one is already running there).
    Blocks briefly for the framework to print its localhost URL, then returns."""
    global _primary
    cwd = os.path.realpath(cwd)
    with _lock:
        ex = _servers.get(cwd)
        if ex and ex.alive():
            _primary = cwd
            return (f"⚙️ Server already running (pid {ex.proc.pid}) in "
                    f"{_safe_rel(cwd)}: {ex.cmd}\nStop it first.")
        _servers.pop(cwd, None)  # drop this dir's previous (exited) entry
        if len(_servers) >= MAX_SERVERS:  # reclaim slots from servers that have exited
            for k in [k for k, s in _servers.items() if not s.alive()]:
                _servers.pop(k, None)
        if len(_servers) >= MAX_SERVERS:
            return f"❌ Too many dev servers running ({MAX_SERVERS}). Stop one first."
        try:
            srv = DevServer(cwd, _selector_cmd(cwd, cmd),
                            project or _safe_rel(cwd), branch)
        except Exception as e:  # noqa: BLE001
            return f"❌ Failed to start: {e}"
        _servers[cwd] = srv
        _primary = cwd

    # Wait for the URL to appear (or for an immediate crash) — but don't block
    # forever; the reader keeps filling in url/port after we return.
    deadline = time.time() + DETECT_TIMEOUT
    while time.time() < deadline:
        if not srv.alive():
            # Keep the exited entry in the registry so the surface can show its
            # status + error output (a stale entry is replaced on the next start).
            tail = "\n".join(list(srv.log)[-15:]) or "(no output)"
            return f"❌ Server exited immediately (code {srv.proc.returncode}):\n{tail}"
        if srv.url:
            break
        time.sleep(0.1)
    where = srv.url or f"http://localhost:{config.PREVIEW_PORT}"
    suffix = "" if srv.url else " (port not detected yet)"
    return (f"✅ Server started (pid {srv.proc.pid}) in {_safe_rel(cwd)}: {cmd}\n"
            f"Preview: {where}{suffix} · /logs to see output.")


def stop(cwd: str) -> str:
    cwd = os.path.realpath(cwd)
    with _lock:
        srv = _servers.pop(cwd, None)
    if not srv:
        return "No server is running here."
    srv.terminate()
    return "🛑 Server stopped."


def state_for(cwd: str) -> dict:
    cwd = os.path.realpath(cwd)
    with _lock:
        srv = _servers.get(cwd)
    return srv.state() if srv else _not_started(cwd)


def list_servers() -> list:
    with _lock:
        srvs = list(_servers.values())
    return [s.state() for s in srvs]


def _tail(cwd: str, n: int) -> list:
    cwd = os.path.realpath(cwd)
    with _lock:
        srv = _servers.get(cwd)
    return srv.tail(n) if srv else []


def stop_all() -> None:
    """Stop every registered dev server. Called on bridge shutdown — servers run
    in their own session (start_new_session=True) so they'd otherwise survive as
    orphans squatting ports the registry can no longer see."""
    global _primary
    with _lock:
        srvs = list(_servers.values())
        _servers.clear()
        _primary = None
    for srv in srvs:
        srv.terminate()


# --- legacy single-server helpers (Mini App + Telegram) --------------------

def start_server(cmd: str, cwd: str) -> str:
    return start(cwd, cmd, project=_safe_rel(cwd))


def stop_server(cwd: "str | None" = None) -> str:
    """Stop the server for ``cwd`` (Mini App passes the chat's project dir so it
    never stops a different project's server); falls back to the primary."""
    target = os.path.realpath(cwd) if cwd else _primary
    if target is None:
        return "No server is running."
    return stop(target)


def server_state(cwd: "str | None" = None) -> dict:
    """Structured status of the server for ``cwd`` (Mini App), else the primary."""
    target = os.path.realpath(cwd) if cwd else _primary
    if target is None:
        return {"status": "not started", "cmd": None, "dir": None, "pid": None}
    s = state_for(target)
    return {"status": s["status"], "cmd": s["cmd"], "dir": s["dir"], "pid": s["pid"]}


def log_tail(n: int = 200, cwd: "str | None" = None) -> list:
    target = os.path.realpath(cwd) if cwd else _primary
    if target is None:
        return []
    return _tail(target, n)


def server_status() -> str:
    with _lock:
        running = [s for s in _servers.values() if s.alive()]
    if not running:
        return "not started"
    parts = ", ".join(f"{s.project or _safe_rel(s.cwd)} ({s.url or '…'})"
                      for s in running)
    return f"{len(running)} running: {parts}"


# --- Telegram handlers (operate on the chat's active project dir) ----------

def handle_server(chat_id: int, arg: str):
    parts = arg.split(maxsplit=1)
    sub = parts[0] if parts else "start"
    rest = parts[1] if len(parts) > 1 else ""
    cwd = state.project_dir(chat_id)
    if sub == "stop":
        send(chat_id, stop(cwd))
    elif sub == "status":
        send(chat_id, "Server: " + server_status())
    elif sub in ("start", ""):
        cmd = rest or config.START_CMD
        send(chat_id, f"🚀 Starting in {_safe_rel(cwd)}: {cmd}")
        send(chat_id, start(cwd, cmd, project=_safe_rel(cwd)))
    else:
        send(chat_id, f"🚀 Starting in {_safe_rel(cwd)}: {arg}")
        send(chat_id, start(cwd, arg, project=_safe_rel(cwd)))


def handle_logs(chat_id: int, arg: str):
    try:
        n = int(arg) if arg else 40
    except ValueError:
        n = 40
    lines = _tail(state.project_dir(chat_id), n)
    body = "\n".join(lines) if lines else "(no server output yet)"
    send(chat_id, f"📄 Last {len(lines)} log line(s):\n\n{body}")
